name: Build Zip

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    name: Build Zip
    runs-on: ubuntu-20.04

    env:
      RELEASE_FILE: galactic-${{github.event.release.tag_name || github.sha}}
      FIRMWARE_NAME: pimoroni-picow_galactic-1.19.7-micropython
      FIRMWARE_URL: https://github.com/pimoroni/pimoroni-pico/releases/download/1.19.7/

    steps:
    - uses: actions/checkout@v2
      with:
        path: galactic
        submodules: true

    - uses: actions/checkout@v2
      with:
        repository: gadgetoid/dir2uf2
        ref: v0.0.1
        path: dir2uf2

    - name: Prepare repository
      shell: bash
      run: |
        python3 -m pip install littlefs-python

    - name: Pack filesystem to .uf2
      shell: bash
      run: |
        ./dir2uf2/dir2uf2 --manifest galactic/uf2-manifest.txt --filename ${{env.RELEASE_FILE}}.uf2 galactic/

    - name: Prepare .zip
      shell: bash
      run: |
        cat uf2-manifest.txt | xargs -I % bash -c "ls -1 %" > zip-manifest.txt
        zip {{env.RELEASE_FILE}}.zip -@ < cat uf2-manifest.txt

    - name: Store .zip as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.RELEASE_FILE}}
        path: galactic/

    - name: Store filesystem .uf2 as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.RELEASE_FILE}}-filesystem-only
        path: ${{env.RELEASE_FILE}}.uf2

    - name: Store full .uf2 as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.FIRMWARE_NAME}}-${{env.RELEASE_FILE}}.uf2
        path: ${{env.FIRMWARE_NAME}}-${{env.RELEASE_FILE}}.uf2

    - name: Upload source .zip
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        asset_path: ${{env.RELEASE_FILE}}.zip
        upload_url: ${{github.event.release.upload_url}}
        asset_name: ${{env.RELEASE_FILE}}.zip
        asset_content_type: application/octet-stream

    - name: Upload filesystem .uf2
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        asset_path: ${{env.RELEASE_FILE}}.uf2
        upload_url: ${{github.event.release.upload_url}}
        asset_name: ${{env.RELEASE_FILE}}-filesystem-only.uf2
        asset_content_type: application/octet-stream

    - name: Upload full firmware .uf2
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        asset_path: ${{env.FIRMWARE_NAME}}-${{env.RELEASE_FILE}}.uf2
        upload_url: ${{github.event.release.upload_url}}
        asset_name: ${{env.FIRMWARE_NAME}}-${{env.RELEASE_FILE}}.uf2
        asset_content_type: application/octet-stream